export const authSelector = (state) => state.auth
export const notifiesSelector = (state) => state.notifies
export const employeesSelector = (state) => state.employees
export const departmentsSelector = (state) => state.departments
export const devicesOfDepartmentsSelector = (state) => state.devicesOfDepartments
export const teamsSelector = (state) => state.teams
export const rolesSelector = (state) => state.roles
export const tasksSelector = (state) => state.tasks
export const proposalsSelector = (state) => state.proposals
export const proposalTypesSelector = (state) => state.proposalTypes
export const approvalStepsSelector = (state) => state.approvalSteps
export const postsSelector = (state) => state.posts